spring:
  profiles:
    active: dev
---
server:
  port: 8001
  address: localhost

mybatis:
  type-aliases-package: com.rui.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  profiles: dev
  application:
    name: HelloSpringCloud-config-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DB01
    username: postgres
    password: Shuuei37

#Eureka注册地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${server.address}:${server.port}
    ip-address: ${server.address}
    prefer-ip-address: true
    metadata-map:
      management.port: ${server.port}

#Actuator
info:
  app.name: dept provider service
  company.name: sap

---
server:
  port: 8001
  address: localhost

mybatis:
  type-aliases-package: com.rui.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
spring:
  profiles: test
  application:
    name: HelloSpringCloud-config-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DB02
    username: postgres
    password: Shuuei37

#Eureka注册地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${server.address}:${server.port}
    ip-address: ${server.address}
    prefer-ip-address: true
    metadata-map:
      management.port: ${server.port}

#Actuator
info:
  app.name: dept provider service
  company.name: sap