spring:
  profiles:
    active: dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: HelloSpringCloud-provider-dept

#Eureka configuration
eureka:  
  client:    
    service-url:   
      defaultZone: http://eureka7001.com:7001/eureka/

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: HelloSpringCloud-provider-dept

#Eureka configuration
eureka:  
  client:    
    service-url:   
      defaultZone: http://eureka7001.com:7001/eureka/
